#端口  
server:  
  port: 8082
  context-path: /job2
  
 
  
  
spring:
  application:
    name: test-job2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: test1
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot
  
